# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The StariumXCV Chronicle
email: socials@stariumxcv.com
description: >- # this means to ignore newlines until "baseurl:"
  StariumXCV is a online sci fi strategy game where you lead a growing empire in a massive shared galaxy.
  This blog follows dev logs and deep dive insights as we build the game.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Minima settings for version 3.0+
author:
  email: "socials@stariumxcv.com"
  name: "Contact Us"

minima:
  skin: dark
  show_excerpts: true
  nav_pages: false
    # - about.markdown   
  social_links:
    - title: Website
      icon: rocket
      url: "https://www.stariumxcv.com"
    - title: IndieDB
      icon: gamepad
      url: "https://www.indiedb.com/games/stariumxcv"
    - title: Discord
      icon: discord
      url: "https://discord.gg/JSB2CTV"
    - title: Facebook
      icon: facebook
      url: "https://www.facebook.com/StariumXCV"
    - title: BlueSky
      icon: bluesky
      url: "https://bsky.app/profile/stariumxcv.bsky.social"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/stariumxcv/"
    - title: TikTok
      icon: tiktok
      url: "https://www.tiktok.com/@stariumxcv"
    - title: YouTube
      icon: youtube
      url: "https://www.youtube.com/channel/UCgEwTnOS1tiU2jlgODSviPQ"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/company/gwythdarian-llc"


# GitHub Pages requires these options to not change
# lsi: false
# safe: true
# source: .
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
